version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: steamAnalytics
    ports:
      - "3307:3306"
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql

