swagger: '2.0'
info:
  title: myapi
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
host: myapi.apigateway.gcpsteamanalytics.cloud.goog
schemes:
  - https
produces:
  - application/json
x-google-management:
  metrics:
    # Defina una métrica para las solicitudes de lectura.
    - name: "read-requests"
      displayName: "Read requests"
      valueType: INT64
      metricKind: DELTA
    # Defina una métrica para las solicitudes de escritura.
    - name: "write-requests"
      displayName: "Write requests"
      valueType: INT64
      metricKind: DELTA
  quota:
    limits:
      # Rate limit para leer
      - name: "read-requests-limit"
        metric: "read-requests"
        unit: "1/min/{project}"
        values:
          STANDARD: 1
      # Rate limit para escribir.
      - name: "write-request-limit"
        metric: "write-requests"
        unit: "1/min/{project}"
        values:
          STANDARD: 1
paths:
  /processGames:
    post:
      summary: Process Games
      operationId: getGamesFromSteam
      x-google-backend:
        address: https://us-central1-gcpsteamanalytics.cloudfunctions.net/process-games-raw
        path_translation: APPEND_PATH_TO_ADDRESS
      x-google-quota:
        metricCosts:
          "write-requests": 1
      security:
        - google_id_token: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /gameDetails:  
    get:
      summary: Get game details by ID
      operationId: getGameDetailsByID
      x-google-backend:
        address: https://us-central1-gcpsteamanalytics.cloudfunctions.net/get-games-raw
        path_translation: APPEND_PATH_TO_ADDRESS
      x-google-quota:
        metricCosts:
          "read-requests": 1
      security:
        - google_id_token: []
      parameters:
        - name: appid
          in: query
          required: true
          type: integer
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /games:
    get:
      summary: Get games
      operationId: getGames
      x-google-backend:
        address: https://us-central1-gcpsteamanalytics.cloudfunctions.net/get-games-raw
        path_translation: APPEND_PATH_TO_ADDRESS
      x-google-quota:
        metricCosts:
          "read-requests": 1
      security:
        - google_id_token: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /processReviews:
    post:
      summary: Process Reviews
      operationId: processReviews
      x-google-backend:
        address: https://us-central1-gcpsteamanalytics.cloudfunctions.net/get-reviews-raw
        path_translation: APPEND_PATH_TO_ADDRESS
      x-google-quota:
        metricCosts:
          "write-requests": 1
      security:
        - google_id_token: []
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /getReviews:
    get:
      summary: Get reviews by app ID, type, and limit
      operationId: getReviews
      x-google-backend:
        address: https://us-central1-gcpsteamanalytics.cloudfunctions.net/get-reviews-raw
        path_translation: APPEND_PATH_TO_ADDRESS
      x-google-quota:
        metricCosts:
          "read-requests": 1
      security:
        - google_id_token: []
      parameters:
        - name: appid
          in: query
          required: true
          type: string
        - name: review_type
          in: query
          required: true
          type: string
        - name: limit
          in: query
          required: true
          type: string
      responses:
        '200':
          description: A successful response
          schema:
            type: string
securityDefinitions:
  # This section configures basic authentication with an API key.
  api_key:
    type: "apiKey"
    name: "key"
    in: "query"
  google_id_token:
    authorizationUrl: ""
    flow: "implicit"
    type: "oauth2"
    x-google-issuer: "https://accounts.google.com"
    x-google-jwks_uri: "https://www.googleapis.com/oauth2/v3/certs"
    x-google-audiences: "848149964201.apps.googleusercontent.com,841077041629.apps.googleusercontent.com"