swagger: '2.0'
info:
  title: myapi
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
host: myapi.apigateway.gcpsteamanalytics.cloud.goog
schemes:
  - https
produces:
  - application/json
paths:
  /processGames:
    post:
      summary: Process Games
      operationId: getGamesFromSteam
      x-google-backend:
        address: https://us-central1-gcpsteamanalytics.cloudfunctions.net/process-games
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /gameDetails/{appid}:  
    get:
      summary: Get game details by ID
      operationId: getGameDetailsByID
      x-google-backend:
        address: https://us-central1-gcpsteamanalytics.cloudfunctions.net/get-games
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: appid
          in: path
          required: true
          type: string
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /games:
    get:
      summary: Get games
      operationId: getGames
      x-google-backend:
        address: https://us-central1-gcpsteamanalytics.cloudfunctions.net/get-games
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /processReviews:
    post:
      summary: Process Reviews
      operationId: processReviews
      x-google-backend:
        address: https://us-central1-gcpsteamanalytics.cloudfunctions.net/get-reviews
        path_translation: APPEND_PATH_TO_ADDRESS
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  /getReviews/{appid}/{review_type}/{limit}:
    get:
      summary: Get reviews by app ID, type, and limit
      operationId: getReviews
      x-google-backend:
        address: https://us-central1-gcpsteamanalytics.cloudfunctions.net/get-reviews
        path_translation: APPEND_PATH_TO_ADDRESS
      parameters:
        - name: appid
          in: path
          required: true
          type: string
        - name: review_type
          in: path
          required: true
          type: string
        - name: limit
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: A successful response
          schema:
            type: string
