data_source games:
  type: bigquery
  connection:
    account_info_json_path: /home/tomi/GCPSteamAnalytics/credentials.json
    auth_scopes:
      - https://www.googleapis.com/auth/bigquery
      - https://www.googleapis.com/auth/cloud-platform
      - https://www.googleapis.com/auth/drive
    project_id: 'pristine-flames-400818'
    dataset: 'games'
soda_cloud:
  host: cloud.us.soda.io
  api_key_id: $SODA_API_KEY_ID
  api_key_secret: $SODA_API_KEY_SECRET