version: '3'

services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    network_mode: host
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: steamAnalytics
