games:
  target: dev
  outputs:
    dev: 
      type: bigquery
      method: service-account
      keyfile: /home/tomi/GCPSteamAnalytics/credentials.json #/opt/airflow/credentials.json
      project: pristine-flames-400818
      dataset: games
      threads: 1
      timeout_seconds: 300
      location: US