name: Go API Cloud Functions

on:  
  push:
  pull_request:
    branches:
      - master
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4.0.1
        with:
          go-version: 1.20.2
      
      - name: Get version Go
        run: go version
          
      - name: Build
        run: |
          cd SteamAPI/ 
          go build 


      - name: Run Tests
        run: go test .
