name: Deploy to Google Cloud Functions

on:
  workflow_run:
    workflows: ["Go API Cloud Functions"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v1
        
      - name: Verify gcloud installation
        run: |
          gcloud --version
          gcloud info
      
      - name: Deploy
        run: |
          cd gcp
          bash deploy.sh
      
      - name: Validate deployment
        run: |
          curl -s "https://gw-7tl86y4z.uc.gateway.dev/test"
