name: Test DAGs

on:
  push:
    paths:
      - 'dags/**'
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verificar python y configuar entorno
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Instalar Dependencias de python
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pip check

      - name: Black PEP 8 Format Test
        run: |
          cd pipeline/
          pip install black
          black . --check

      - name: Correr Tests Unitarios
        env:
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
        run: |
          cd pipeline/src/tests
          pytest -v || exit

        
